### ISSUE TITLE
Image embedding using transclusion syntax

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/remark-wiki-link-plus#1]
I suggest focusing only on images because for other doc types we don't yet know how to render nicely.

## Acceptance

* [x] `![[abc.png]]` works **✅ 2022-08-11**
* [x] `![[abc.jpg]]` works **✅ 2022-08-11**
* [x] etc for all image endings e.g. those listed on https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types (with any alternatives e.g. jpg and jpeg **✅2022-08-17 all image endings supported ~~🚧 2022-08-11 .jpeg, .apng, .webp, .avif, .gif, .svg, .bmp, .ico**
* [x] For non image endings (or endings not in the list) output a useful error message *in the markdown* e.g. "Document type {extension} is not support yet for transclusion" and console warn during the build (?)

support added and works after last commit [cfa0658](https://github.com/flowershow/remark-wiki-link-plus/commit/cfa0658eab34d5770cc66a041e6aef42023821e2)

## Tasks

* [x] Analysis and estimate
* [x] Implement
* [x] Parse image wikilinks `![[Image.png]]` to `<img src="[some folder]/image.png" className="internal" />`
   * [x] supports png, jpg and jpeg files
* [x] bump package to version v1.0.2
* [x] update readme 

## Test screenshot

(parses a wiki link that is an image)
![Screen Shot 2022-08-11 at 4 19 40 PM](https://user-images.githubusercontent.com/42637597/184132786-60dd9b5e-b500-42af-ab11-5fa04a5f2f0c.png)

## Result screenshot

![Screen Shot 2022-08-11 at 4 33 25 PM](https://user-images.githubusercontent.com/42637597/184134275-e388b6a4-3dd6-45d4-b4b6-3f4beba67007.png)

**Comment by rufuspollock** [comment]
@khalilcodes please update each day when you do work on this 🙂

**Comment by rufuspollock** [comment]
@khalilcodes can you update acceptance and we close if done?

**Comment by khalilcodes** [comment]
This feature is supported now.

**Comment by rufuspollock** [comment]
@khalilcodes can you detail what image endings you supported? e.g. did you support `webp` - and did you search for a common list of image file endings?

**Comment by abhishekgahlot** [comment]
<img width="648" alt="Screenshot 2022-08-17 at 6 56 07 PM" src="https://user-images.githubusercontent.com/1985457/185145857-536b3b4d-ef06-441e-bc7a-a04d0b5e69cd.png">

The current code fails because we have two selection one is finding out if the tag is image or not.
Right now there is no way to tell how a tag is not image with `![[]]` we need to extend the code functionality.

**Comment by khalilcodes** [comment]
@rufuspollock further research by @abhishekgahlot on tokenization are here https://github.com/landakram/remark-wiki-link/issues/21 which I am looking into
