### ISSUE TITLE
PDF embedding

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/remark-wiki-link-plus#4]
![[xyz.pdf]] turns into a pdf embed that works in major browsers.

## Acceptance

* [x] `![[xyz.pdf]]` turns into a pdf embed ...

## Tasks

* [x] Research how you can display a pdf in html in major browser (maybe there are no longer good ways) and recommend
  * [x] Identify fallbacks - maybe we just display a pdf link instead of embed
* [x] implement

**Comment by abhishekgahlot** [comment]
PDF embedding is done via `embed` in the following PR: https://github.com/flowershow/remark-wiki-link-plus/pull/6
